image: mono
clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly  
definitions:
  services:
    docker:
      memory: 4096
  caches:
    nuget: src/packages
pipelines:
  branches:
# uncomment next line to build releases as well as prereleases
#    '{release,prerelease}':
    master:
        - step: 
           size: 2x
           script:
           - apt-get update 
           - nuget sources add -Name real-trivident -Source $PRIVATE_REPO_REAL_URL -UserName $PRIVATE_REPO_REAL_USERNAME -Password $PRIVATE_REPO_REAL_PASSWORD
           - nuget restore $BITBUCKET_CLONE_DIR/src/Dyndle.Tools.sln 
           - msbuild /p:Configuration="Release" /p:Branch="$BITBUCKET_BRANCH" /p:Bitbucket="true" $BITBUCKET_CLONE_DIR/src/Dyndle.Tools.sln
           - curl -X POST https://content.dropboxapi.com/2/files/upload --header "Authorization: Bearer $DROPBOX_TOKEN" --header "Dropbox-API-Arg: {\"path\": \"/dyndle.com/dyndle.exe\",\"mode\": \"overwrite\",\"autorename\": false,\"mute\": true,\"strict_conflict\": false}" --header "Content-Type: application/octet-stream" --data-binary $BITBUCKET_CLONE_DIR/src/Dyndle.Tools.CLI/bin/Release/artifacts/dyndle.exe
           artifacts:
            - src/Dyndle.Tools.CLI/bin/Release/artifacts/dyndle.exe
