image: mono
clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly  
definitions:
  services:
    docker:
      memory: 4096
  caches:
    nuget: src/packages
pipelines:
  branches:
# uncomment next line to build releases as well as prereleases
#    '{release,prerelease}':
    feature/pipeline:
        - step: 
           size: 2x
           script:
           - apt-get update 
           - nuget sources add -Name privaterepo2 -Source $PRIVATE_NUGET_URL -UserName $PRIVATE_NUGET_USERNAME -Password $PRIVATE_NUGET_PASSWORD
           - nuget restore $BITBUCKET_CLONE_DIR/src/Dyndle.Tools.sln 
           - msbuild /p:Configuration="Release" /p:Branch="$BITBUCKET_BRANCH" $BITBUCKET_CLONE_DIR/src/Dyndle.Tools.sln 
